name: KingOfTheHill
version: '${project.version}'
main: dev.sasukector.hundreddaysuhc.KingOfTheHill
api-version: 1.17
authors: [ Sasukector ]
description: This is the core plugin for KingOfTheHill
website: https://sasukector.dev
commands:
  winners:
    description: Command to see winners
    usage: /winners
  game:
    description: Command to manage game
    usage: /game [option] [subOption]